### ISSUE TITLE
datetime picker interoperability with date picker causing css errors

### ISSUE THREAD

**Issue by w3sami** [h2qutc/angular-material-components#256]
hi, dt picker is exactly what i need, but having it on the same page with normal datepicker is causing problems. it break both d and dt pickers, depending on what you select first.

my markup
1. dt picker
      <mat-form-field>
        <mat-label>{{ 'Material dl' | trans }}</mat-label>
        <input
          matInput
          [ngxMatDatetimePicker]="materialDl"
          [formControl]="campaign.materialDl"
          name="materialDl"
          required
        />
        <mat-datepicker-toggle
          matSuffix
          [for]="$any(materialDl)"
        ></mat-datepicker-toggle>
        <ngx-mat-datetime-picker #materialDl></ngx-mat-datetime-picker>
      </mat-form-field>
2 date picker
      <mat-form-field>
        <mat-label>{{ 'Start date' | trans }}</mat-label>
        <input
          matInput
          [matDatepicker]="startDate"
          [formControl]="campaign.startDate"
          required
        />
        <mat-datepicker-toggle
          matSuffix
          [for]="startDate"
        ></mat-datepicker-toggle>
        <mat-datepicker #startDate></mat-datepicker>
      </mat-form-field>

if you select a date with 2. and then go to select a date time you end up with totally messed up dt picker.

![image](https://user-images.githubusercontent.com/3714721/159630440-f85b4176-2b81-4bb6-9710-a10e97fe4cc6.png)

( sometimes it helps to click on the body, and when focus not on date picker, it's all fine)

and the other way, if you select a dt and then go select a date, the current day, gets squished unreadable. not nearly as annoying but not nice either

![image](https://user-images.githubusercontent.com/3714721/159630811-dcb47d0d-05dd-4d96-bedd-2e4d6f3cba0a.png)

using the latest packages

    "@angular/material": "^13.2.1",
    "@angular-material-components/datetime-picker": "^7.0.1",

and normal viewencapsulation on this page

**Comment by brandon-morgan** [comment]
@w3sami, I'm having the same issue and it appears to be caused by the `.mat-calendar-body-cell` mistakenly getting the position of `absolute` when I change to relative it fixes the issue at least for me. Not an actual fix of course but seems to be an issue with css inheritance or something related when both exist on same screen.

**Comment by w3sami** [comment]
@brandon-morgan thank you so much!

I resolved the issue with
ngx-mat-calendar {
  .mat-calendar-body-cell {
    position: relative !important;
  }
}
mat-calendar {
  .mat-calendar-body-cell {
    position: absolute !important;
  }
}
in my global styles
\0/
leaving this open, since this shouldn't be fixed in userland code

**Comment by functionportal** [comment]
@w3sami 
Thank you. That fixed my layout issue, but the iconography issue remains.
