### ISSUE TITLE
Transparent background in popup

### ISSUE THREAD

**Issue by cperezabo** [h2qutc/angular-material-components#348]
Hi, I updated Angular and Material to v16.2.0 and datetime-picker to v16.0.1
I don't know what changed, but I'm getting a transparent background now. Any idea? 
<img width="468" alt="CleanShot 2023-08-14 at 18 59 08@2x" src="https://github.com/h2qutc/angular-material-components/assets/3604722/68cae2c4-05a7-4933-af16-70cf31eb6bfc">

Edit: In fact, confirmation button is missing, the popup won't close and there are no errors in console.

**Comment by AdamsContreras999** [comment]
yes for me is too same error

**Comment by cperezabo** [comment]
I updated from v9 to v16, so I don't know if this was working in v15. I would like to find where it broken

**Comment by AdamsContreras999** [comment]
in fact when all the angular dependencies were in version 16.1.0 it was working fine but angular was updated to version 16.2.0 and there it presented this error.

**Comment by tfiil** [comment]
I have also experienced the same issue after the upgrade.

However something strange I've noticed is that if I click a "normal" mat-datepicker in the same application and subsequently click the ngx-mat-datetime-picker it will be styled correctly. 

If no normal datepicker pop-up has been previously shown it will be transparent.

**Comment by cperezabo** [comment]
Maybe the issue comes from Material? I haven't got time to debug it deeply. But by what you say seems that the problem can come from upstream

**Comment by francobasilico** [comment]
There are some updates on 16.2.1.
https://github.com/angular/components/commit/0c4f947cdf511750b2e62f793e23b6bcc5678ab5#diff-70165fe5f110c97706ce01e94ddf46c6aad553a1c6948dabcd60b14ad6d734b6
Maybe this fix it, will try to give it a go soon

**Comment by francobasilico** [comment]
I quickly tried it persists in 16.2.1

**Comment by serg-mois-capital** [comment]
Faced the same problem. Does anybody have any workaround? It's a critical issue.

**Comment by cperezabo** [comment]
As a workaround I've added some styles globally, not all of them but enough for what I need in the meantime.


```scss
.mat-datepicker-content {
  box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
  background-color: #fff;
  color: #000000de
}

.mat-calendar-body-selected {
  background-color: #007f51;
  color: #fff;
}

.mat-calendar-body-cell-content {
  border: none !important;
}
```

**Comment by serg-mois-capital** [comment]
@h2qutc need your help)

**Comment by francobasilico** [comment]
Thank you @cperezabo (gracias guacho)
I've tried those and work. As you said it fix some cases, for example, I have actions and have to add extra classes.
 thanks for the code.

**Comment by pantonis** [comment]
Is there any fix for this planned?

**Comment by pkgwarek** [comment]
Issue still exists.

**Comment by John-Santacruz** [comment]
Please fix this issue.

**Comment by Skelyos** [comment]
Strange thing I noticed: if you open a pure Angular datepicker & then open up this datetime picker all the styles are temporarily added back in again until you refresh the page. 

Not sure how useful this is but may help debug the problem.

**Comment by shivamkatyan** [comment]
I was facing the same issue, I have fixed it by adding the missing CSS

**Comment by TheDeadCode** [comment]
Still persists

**Comment by pkitatta** [comment]
Any help on this. I have the same problem.

**Comment by JUBINBIJU** [comment]
Same issue for me

**Comment by JUBINBIJU** [comment]
I degraded the version from 16.2 to 16.1 and then to 16.0 still its not working. Did that work for anyone?

**Comment by JUBINBIJU** [comment]
> Strange thing I noticed: if you open a pure Angular datepicker & then open up this datetime picker all the styles are temporarily added back in again until you refresh the page.
> 
> Not sure how useful this is but may help debug the problem.

yes i was also able to recreate that

**Comment by AlexElin** [comment]
Could somebody provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (MRE)?

The issue isn't reproduced at the [library site](https://h2qutc.github.io/angular-material-components/#/datetimepicker). So, having the MRE would be helpful

**Comment by Klaster1** [comment]
@AlexElin please see [the branch I made](https://github.com/Klaster1/angular-material-components/tree/angular-17-update), you can observe the effect clearly there.

**Comment by Guerric-P** [comment]
Why this bug appears only now? It's been since Angular 11 and the deprecation of the `extractCss` configuration property that the styles are not bundled all together in a global CSS file, but dynamically inserted in a `style` tag when the component shows.

**Comment by stnor** [comment]
Another repro: https://stackblitz.com/edit/angular-cpmuqe

**Comment by stnor** [comment]
A simple workaround is to open and close a datepicker to load the styles. This isn't visible to the user. No need for global style hacks.
````typescript
   //Workaround for https://github.com/h2qutc/angular-material-components/issues/348
   @ViewChild('hiddenpicker')
   private readonly hiddenpicker: MatDatepicker<null>

   ngOnInit() {
        this.hiddenpicker.open();
        this.hiddenpicker.close();
   }
````

**Comment by arjen-t** [comment]
The issue does exist, and version 16.x doesn't function well with Angular Material versions >= 16.*. I also encounter styling collisions when using the native Angular Material datepicker alongside the datetimepicker on the same page. Considering that in version 16.x, the default start date is broken (https://github.com/h2qutc/angular-material-components/issues/356), we addressed the issue as follows:

Downgrade to latest version 9.* to maintain support for the default startdate.
Add styling to the component, scoped to the datetimepicker (ngx-mat-datetime-content), to ensure it works with Angular Material >= 16.*.

```
::ng-deep {
  .mat-mdc-form-field-icon-suffix {
    .mat-mdc-icon-button.mat-mdc-button-base {
      --mdc-icon-button-state-layer-size: 36px;
      width: var(--mdc-icon-button-state-layer-size) !important;
      height: var(--mdc-icon-button-state-layer-size) !important;
      padding: 6px !important;
    }
  }

  //Fix datepicker styling in ngx-mat-calendar untill we can migratet to 16.x fixed all bugs
  ngx-mat-datetime-content {
    &.mat-datepicker-content {
      box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024,
        0 1px 10px #0000001f;
      background-color: #fff;
      color: #000000de;

      .mat-calendar-body-cell {
        position: relative;
      }

      .mat-calendar-body-cell:hover {
        .mat-calendar-body-cell-content:not(.mat-calendar-body-selected) {
          background-color: #258ea88d;
        }
      }

      .mat-calendar-body-selected {
        background-color: #258ea8;
        color: #fff;
      }

      .mat-calendar-body-today.mat-calendar-body-selected {
        box-shadow: inset 0 0 0 1px #fff;
      }
    }
  }
}
```

Considering that people invest their free time in maintaining this package, it would be greatly appreciated if the mentioned issues could be resolved. The current state is starting to feel broken.

**Comment by yousafzainasir8** [comment]
still facing this issue

**Comment by Klaster1** [comment]
@stnor I tried the open/close hack and it did not help. Even after manually opening an Angular Material date picker, the ngx-mat-datetime-picker is still missing styles.

**Comment by Nivijoy** [comment]
Overwrite the style 
::ng-deep .mat-datepicker-content .mat-calendar {
  background-color: #c2185b;
}

::ng-deep .time-container {
  background-color: #c2185b;
}

::ng-deep .mat-calendar-body-cell-content.mat-focus-indicator {
  color: white;
  border: none;
}

**Comment by geckodesalpes** [comment]
> As a workaround I added some styles globally, I've not added all the styles at all, but enough for what I need in the meantime.
> 
> ```css-scss
> .mat-datepicker-content {
>   box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
>   background-color: #fff;
>   color: #000000de
> }
> 
> .mat-calendar-body-selected {
>   background-color: #007f51;
>   color: #fff;
> }
> 
> .mat-calendar-body-cell-content {
>   border: none !important;
> }
> ```

Based on your workaround, it is also possible to directly use the mat- variables in order to support theming:
```
.mat-datepicker-content, .time-container {
  box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);
  display: block;
  border-radius: 4px;
  background-color: var(--mat-datepicker-calendar-container-background-color);
  color: var(--mat-datepicker-calendar-container-text-color);
}

.mat-calendar-body-cell-content {
  color: var(--mat-datepicker-calendar-date-text-color);
  border-color: var(--mat-datepicker-calendar-date-outline-color)
}

.mat-calendar-body-selected {
  background-color: var(--mat-datepicker-calendar-date-selected-state-background-color);
  color: var(--mat-datepicker-calendar-date-selected-state-text-color);
}

.mat-calendar-body-cell-content {
  border: none !important;
}

.mat-calendar-body-cell:not(.mat-calendar-body-disabled):hover > .mat-calendar-body-cell-content:not(.mat-calendar-body-selected):not(.mat-calendar-body-comparison-identical) {
  background-color: var(--mat-datepicker-calendar-date-hover-state-background-color);
}

.mat-calendar-arrow {
  fill: var(--mat-datepicker-calendar-period-button-icon-color);
}
```

**Comment by SeraphCoding** [comment]
> > As a workaround I added some styles globally, I've not added all the styles at all, but enough for what I need in the meantime.
> > ```
> > .mat-datepicker-content {
> >   box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
> >   background-color: #fff;
> >   color: #000000de
> > }
> > 
> > .mat-calendar-body-selected {
> >   background-color: #007f51;
> >   color: #fff;
> > }
> > 
> > .mat-calendar-body-cell-content {
> >   border: none !important;
> > }
> > ```
> 
> Based on your workaround, it is also possible to directly use the mat- variables in order to support theming:
> 
> ```
> .mat-datepicker-content, .time-container {
>   box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);
>   display: block;
>   border-radius: 4px;
>   background-color: var(--mat-datepicker-calendar-container-background-color);
>   color: var(--mat-datepicker-calendar-container-text-color);
> }
> 
> .mat-calendar-body-cell-content {
>   color: var(--mat-datepicker-calendar-date-text-color);
>   border-color: var(--mat-datepicker-calendar-date-outline-color)
> }
> 
> .mat-calendar-body-selected {
>   background-color: var(--mat-datepicker-calendar-date-selected-state-background-color);
>   color: var(--mat-datepicker-calendar-date-selected-state-text-color);
> }
> 
> .mat-calendar-body-cell-content {
>   border: none !important;
> }
> 
> .mat-calendar-body-cell:not(.mat-calendar-body-disabled):hover > .mat-calendar-body-cell-content:not(.mat-calendar-body-selected):not(.mat-calendar-body-comparison-identical) {
>   background-color: var(--mat-datepicker-calendar-date-hover-state-background-color);
> }
> ```

Amazing workaround for now! For me the chevron-up icons for the time selector are also missing. Is this related to this issue? The original issue has its chevrons. Anyone else experiencing that?

**Comment by geckodesalpes** [comment]
@SeraphCoding Assuming my current understanding of the issue, this may be linked, as my feeling is that the issue could come from breaking changes regarding encapsulation in Angular latest versions.

That said, the time picker buttons are not based on the same principle as the one upper right for the calendar (those last one use borders and 45° rotation). The time picker works with a traditional `mat-icon`:
![image](https://github.com/h2qutc/angular-material-components/assets/11677246/c81c8081-f884-4778-aed3-4c73288349df)

Assuming on the original capture, all dependencies are at the latest, there should be a way to make it work if the **mat-icon** module is properly imported and configured in your project / targetted module.
If you use custom icon provider (like FA) for mat-icon this may be more tricky to find a nice workaround as they are using the old way where the icon name is set as content and not HTML attribute, eliminating a pure CSS workaround possibility. At last should be possible but extremely dirty to do something in vanilla JS / JQuery 🤐.

**Comment by samuele-ruffino96** [comment]
> .mat-datepicker-content {
>   box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
>   background-color: #fff;
>   color: #000000de
> }
> 
> .mat-calendar-body-selected {
>   background-color: #007f51;
>   color: #fff;
> }
> 
> .mat-calendar-body-cell-content {
>   border: none !important;
> }

Thank you for workaround. Just a tip for ones who has noticed issues with disabled labels style, in fact for some reason it seems the style for disabled days/years is still missing. Below an example:

**How it was before**
![image](https://github.com/h2qutc/angular-material-components/assets/74648681/957ff1a6-4a20-4e17-ac4f-040d1c36d9e9) | ![image](https://github.com/h2qutc/angular-material-components/assets/74648681/d098c5c7-8493-47d2-8bd8-12927f7c8cd4)

How it looks now
![image](https://github.com/h2qutc/angular-material-components/assets/74648681/4d234034-5bc8-4e02-b489-c5eb7de9435f)|![image](https://github.com/h2qutc/angular-material-components/assets/74648681/f25980ac-f3c6-4315-9002-0c05f0d36c44)

As you can see, only the chevrons disabled style is still present, so i added this class below as temporary workaround, hope it'll help you.

<pre>
.mat-calendar-body-disabled>.mat-calendar-body-cell-content:not(.mat-calendar-body-selected):not(.mat-calendar-body-comparison-identical) {
    color: var(--mat-datepicker-calendar-date-disabled-state-text-color);
}
</pre>

**Comment by rhwilburn** [comment]
For me the solution was:

```
/*
 Note: div in the query selector below only to get precidence over the default .mat-datepicker-content-container 
by being more specific. This isn't required for background-color but was required for me to override other things in
 that container 
*/
div.mat-datepicker-content-container {
  background-color: var(--background-color);
  }
```

Using a variable isn't needed as such; could just be `background-color: red;` etc

**Comment by m-akinc** [comment]
The datetime picker includes a [theming support file](https://github.com/h2qutc/angular-material-components/blob/v16.0.1/projects/datetime-picker/src/lib/_datepicker-theme.scss) that was copied directly from [Angular material](https://github.com/angular/components/blob/16.1.8/src/material/datepicker/_datepicker-theme.scss), but in Angular material version 16.2, the [implementation](https://github.com/angular/components/blob/16.2.0/src/material/datepicker/_datepicker-theme.scss) changed. This datetime picker package is still using the old version of the file, and it doesn't work with the token-based system of v16.2+.

The only way the styling looks right is if the Angular material 16.2+ datepicker gets loaded first, in which case the `'mat-datepicker'` theme styles get initialized correctly.

**Comment by m-akinc** [comment]
@h2qutc I was going to try to update `_datepicker-theme.scss` to see if that would solve this issue, but I had some concerns:
- there have been no commits since 8/1/23
- it looks like you haven't been active on GitHub since then, so I wonder if you're still maintaining this repo
- there's no CONTRIBUTING file
- running `npm install` results in dependency conflict errors
- even the newest release of `tsickle` (two years old) is incompatible with the version of Typescript needed by other dependencies
- running `npm run test` doesn't find any tests to run
- running `npm run e2e` fails because the version of ChromeDriver doesn't support recent versions

If you are still maintaining this repo, let me know so I can try to help resolve this issue that so many users are running into.

**Comment by Prasanna-Sridharan** [comment]
> > .mat-datepicker-content {
> > box-shadow: 0 2px 4px -1px #3, 0 4px 5px #24, 0 1px 10px #0000001f;
> > background-color: #fff;
> > color: #000000de
> > }
> > .mat-calendar-body-selected {
> > background-color: #007f51;
> > color: #fff;
> > }
> > .mat-calendar-body-cell-content {
> > border: none !important;
> > }
> 
> Thank you for workaround. Just a tip for ones who has noticed issues with disabled labels style, in fact for some reason it seems the style for disabled days/years is still missing. Below an example:
> 
> **How it was before** ![image](https://private-user-images.githubusercontent.com/74648681/301781547-957ff1a6-4a20-4e17-ac4f-040d1c36d9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTU1NDIsIm5iZiI6MTcxMjA5NTI0MiwicGF0aCI6Ii83NDY0ODY4MS8zMDE3ODE1NDctOTU3ZmYxYTYtNGEyMC00ZTE3LWFjNGYtMDQwZDFjMzZkOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIyMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5Y2E5ZTY0YmQ2OTE1YmM4Y2RmNDA1N2VhNGYxYmFlMDAwZDgzNjExNzAwMTk2ZTFmMzhjOTJlODUzODUxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jzPpIz0Qbwozo1AhEC-VMojcT72nHHlbWHfPmJvD9vw) | ![image](https://private-user-images.githubusercontent.com/74648681/301781755-d098c5c7-8493-47d2-8bd8-12927f7c8cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTU1NDIsIm5iZiI6MTcxMjA5NTI0MiwicGF0aCI6Ii83NDY0ODY4MS8zMDE3ODE3NTUtZDA5OGM1YzctODQ5My00N2QyLThiZDgtMTI5MjdmN2M4Y2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIyMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjAxZjdiZGQ2ZjExMzJmZjg3NDI1YWU4ODA5MWM1NTVmY2IwNmI2MTEwNTI2NWEyNWFlNTI3YTA4MmRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asNjZFjODpHpw8tMOi7XNRYrszJtauwT1uZsT8XZtbQ)
> 
> How it looks now ![image](https://private-user-images.githubusercontent.com/74648681/301782967-4d234034-5bc8-4e02-b489-c5eb7de9435f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTU1NDIsIm5iZiI6MTcxMjA5NTI0MiwicGF0aCI6Ii83NDY0ODY4MS8zMDE3ODI5NjctNGQyMzQwMzQtNWJjOC00ZTAyLWI0ODktYzVlYjdkZTk0MzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIyMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzZjOGViZjNiMzY0NDBjZWZiNmYyNmEyNDdlMjQ2MzVkZjQ4ZTJlYmFiMTQyNjZiNmM5OWI0NTI3MTdjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eim9x57PdJnJVAeOlxRaPIWbH7jtWaQ2km-rD0auEn4)|![image](https://private-user-images.githubusercontent.com/74648681/301783024-f25980ac-f3c6-4315-9002-0c05f0d36c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTU1NDIsIm5iZiI6MTcxMjA5NTI0MiwicGF0aCI6Ii83NDY0ODY4MS8zMDE3ODMwMjQtZjI1OTgwYWMtZjNjNi00MzE1LTkwMDItMGMwNWYwZDM2YzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIyMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGU2ZTVhMTZiYmViYjA1Y2Q4YmY1MDE2MTgyMTE0ZWM2ZWI4NTY5Y2VjMjc2YTVmNGUyNzY1MmQ0ODlkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzkF8GNE10GH56LLesVwlOYMKYYLD5QfjT4rA6UW9O0)
> 
> As you can see, only the chevrons disabled style is still present, so i added this class below as temporary workaround, hope it'll help you.
> 
> .mat-calendar-body-disabled>.mat-calendar-body-cell-content:not(.mat-calendar-body-selected):not(.mat-calendar-body-comparison-identical) {
>     color: var(--mat-datepicker-calendar-date-disabled-state-text-color);
> }

Thanks for the workaround fix along with previous contributors styles.. saved a lot of time !!

I just added below as well to not show cursor pointer on disabled dates:
button.mat-calendar-body-disabled {
    cursor: default !important;
}

**Comment by tito-cr** [comment]
This seems to be working in Angular 17. I haven't tested it a lot, just basically commented out the workaround code.

**Comment by sousawalker** [comment]
> As a workaround I've added some styles globally, not all of them but enough for what I need in the meantime.
> 
> ```css-scss
> .mat-datepicker-content {
>   box-shadow: 0 2px 4px -1px #0003, 0 4px 5px #00000024, 0 1px 10px #0000001f;
>   background-color: #fff;
>   color: #000000de
> }
> 
> .mat-calendar-body-selected {
>   background-color: #007f51;
>   color: #fff;
> }
> 
> .mat-calendar-body-cell-content {
>   border: none !important;
> }
> ```

This worket for me. Thankyou.

**Comment by AlexElin** [comment]
Looks like this project is not maintained.

I've found another library which contains material-like datetimepicker and many other useful components.
Here it is: https://ng-matero.github.io/extensions/components/datetimepicker.

**Comment by SeraphCoding** [comment]
> Looks like this project is not maintained.
> 
> I've found another library which contains material-like datetimepicker and many other useful components. Here it is: https://ng-matero.github.io/extensions/components/datetimepicker.

This makes life a lot easier. Great mention!

**Comment by annaluzfisher** [comment]
For anyone looking at v 17 I was missing the mixins in my custom theme file. you need them for each item and if missing were causing the backgrounds to be transparent and other issues :

@use "@angular/material" as mat;

$my-theme: mat.define-light-theme(
  (
    color: (
      primary: $primaryPalette,
      accent: $accentPalette,
      warn: $warnPalette,
    ),
  )
);

@include mat.core();
@include mat.core-theme($my-theme);
@include mat.form-field-theme($my-theme);
@include mat.progress-spinner-theme($my-theme);
@include mat.tabs-theme($my-theme);
@include mat.button-theme($my-theme);
@include mat.checkbox-theme($my-theme);
@include mat.datepicker-theme($my-theme);
@include mat.input-theme($my-theme);
@include mat.select-theme($my-theme);
@include mat.slider-theme($my-theme);
@include mat.slide-toggle-theme($my-theme);

**Comment by adilorenzodema** [comment]
Any update about fix for Angular 16?
