### ISSUE TITLE
Weird peer dependency warnings

### ISSUE THREAD

**Issue by jpike88** [h2qutc/angular-material-components#53]
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/platform-browser@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/common@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/core@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/forms@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/material@0.0.0-PLACEHOLDER but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of @angular/cdk@0.0.0-PLACEHOLDER but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/datetime-picker@2.0.4 requires a peer of tslib@0.0.0-TSLIB but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/moment-adapter@2.0.2 requires a peer of @angular/common@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/moment-adapter@2.0.2 requires a peer of @angular/core@0.0.0-NG but none is installed. You must install peer dependencies yourself.

**Comment by h2qutc** [comment]
Can you provide your package.json please so that I can reproduce this bug ?

**Comment by jpike88** [comment]
This has nothing to do with my package.json, this issue is in the package.json of the latest release of ```@angular-material-components/datetime-picker``` on npm.

This is from its package.json:

```
"peerDependencies": {
    "@angular/platform-browser": "0.0.0-NG",
    "@angular/common": "0.0.0-NG",
    "@angular/core": "0.0.0-NG",
    "@angular/forms": "0.0.0-NG",
    "@angular/material": "0.0.0-PLACEHOLDER",
    "@angular/cdk": "0.0.0-PLACEHOLDER",
    "tslib": "0.0.0-TSLIB"
  },
```

**Comment by krishna217** [comment]
Facing same issue

> Can you provide your package.json please so that I can reproduce this bug ?

I'm also facing the same issue. Issue is in the latest release on npm

**Comment by jpike88** [comment]
Ugh I’ve had enough of how slow things are going here. This is basic stuff. I’m going to fork if in a week this isn’t resolved.

**Comment by h2qutc** [comment]
Can you let me know which version of angular and angular material in your application ?

**Comment by krishna217** [comment]
> Can you let me know which version of angular and angular material in your application ?

Try this package.json
{
  "name": "datepicker-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-material-components/datetime-picker": "^2.0.4",
    "@angular/animations": "~9.1.3",
    "@angular/common": "~9.1.3",
    "@angular/compiler": "~9.1.3",
    "@angular/core": "~9.1.3",
    "@angular/forms": "~9.1.3",
    "@angular/platform-browser": "~9.1.3",
    "@angular/platform-browser-dynamic": "~9.1.3",
    "@angular/router": "~9.1.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.3",
    "@angular/cli": "~9.1.3",
    "@angular/compiler-cli": "~9.1.3",
    "@angular/language-service": "~9.1.3",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.14.1",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

**Comment by jpike88** [comment]
I feel like my [comments](https://github.com/h2qutc/angular-material-components/issues/53#issuecomment-640031584) aren't event being read. Let me repeat.

This has **nothing** to do with the version of people's angular. The problem is with this library.

step 1: Download latest `@angular-material-components/datetime-picker` from npm.
step 2: Look at the package.json in the downloaded package.
step 3: Release a new version where the package.json isn't filled with dummy data.

**Comment by h2qutc** [comment]
@krishna217 I don't see @angular/material and @angular/cdk ? Did you miss those packages ?

**Comment by krishna217** [comment]
> @krishna217 I don't see @angular/material and @angular/cdk ? Did you miss those packages ?

Sorry about that i updated the my [comment](https://github.com/h2qutc/angular-material-components/issues/53#issuecomment-644516202) with package.json

**Comment by krishna217** [comment]
@h2qutc  Any progress on this ? Also while upgrading to angular 10 it throws an error due to these incompatible dependencies.

**Comment by jpike88** [comment]
> @krishna217 I don't see @angular/material and @angular/cdk ? Did you miss those packages ?

What???? Why does that matter? What do those libraries have to do with the problem? Please read what I wrote earlier in the thread because this is becoming a waste of everyone’s time.

**Comment by llyrowenjones** [comment]
I'm also facing the same issue;

npm ERR! peer dep missing: @angular/cdk@0.0.0-PLACEHOLDER, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: @angular/common@0.0.0-NG, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: @angular/common@0.0.0-NG, required by @angular-material-components/moment-adapter@2.0.2
npm ERR! peer dep missing: @angular/core@0.0.0-NG, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: @angular/core@0.0.0-NG, required by @angular-material-components/moment-adapter@2.0.2
npm ERR! peer dep missing: @angular/forms@0.0.0-NG, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: @angular/material@0.0.0-PLACEHOLDER, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: @angular/platform-browser@0.0.0-NG, required by @angular-material-components/datetime-picker@2.0.4
npm ERR! peer dep missing: tslib@0.0.0-TSLIB, required by @angular-material-components/datetime-picker@2.0.4

**Comment by llyrowenjones** [comment]
Issue has been resolved in version 4.0.0, thanks!

https://github.com/h2qutc/angular-material-components/issues/65#issuecomment-655031071

**Comment by shalltalk** [comment]
Version 2.0.4 still has this problem. Any plan to fix it? Thanks.
https://github.com/h2qutc/angular-material-components/blob/master/projects/datetime-picker/package.json

**Comment by shalltalk** [comment]
And a reminder, without the fix, application that uses this lib cannot be dockerized. Please take a look when you get a chance @h2qutc 
I can fork it if that's easier for you to merge the fix.

**Comment by Carbammato** [comment]
Is there any kind of support you'll provide to those legacy application that uses older versions of Angular?
I'm finding myself with an error on an Angular 8 application, and I wish there's a way to release a 2.0.5 just to update the package.json of the library instead to have to fork the project by myself just for the sake of it.

**Comment by Magoloric** [comment]
This is still a problem in 2.x. I have no ability nor will to upgrade angular for the sake of just this component. Not willing to support legacy versions is understandable, but then you should remove older versions from the table, so developers are not misled into believing that they can use it without issues on older versions of Angular. Because 2.x versions are simply broken because of this issue.

If there's any alternative solutions, do let me know.

**Comment by vshmoylov** [comment]
@Magoloric @shalltalk As a workaround for this particular case, you can use `--legacy-peer-deps` flag for `npm install` command so npm will ignore broken peer dependencies (not a best approach though).
Also, there is a possibility to add library code from node_modules to some folder of your repo, for example, `lib/@angular-material-components/datetime-picker`. Then patch package.json and do local npm install from there: `npm i --save ./lib/@angular-material-components/datetime-picker`.

**Comment by Mihirpatel2005** [comment]
Very good web page, thank oneself for the exciting material for guaranteed I am going to be back.https://betterprogramming.pub/the-step-by-step-guide-to-understanding-and-adopting-npm-7-914504f7090f

**Comment by roma2341** [comment]
Only i don't understand what mean "0.0.0-NG" ?

**Comment by vshmoylov** [comment]
@roma2341 this is because author of the package explicitly broke old versions to "deprecate" them in such way. If you are looking for a solution to overcome this, you can try running `npm install --legacy-peer-deps`
